/*
 * This file is part of SQL Workbench/J, https://www.sql-workbench.eu
 *
 * Copyright 2002-2020 Thomas Kellerer.
 *
 * Licensed under a modified Apache License, Version 2.0 (the "License")
 * that restricts the use for certain governments.
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.sql-workbench.eu/manual/license.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * To contact the author please send an email to: support@sql-workbench.eu
 */
package workbench.gui.components;

import javax.swing.JPanel;

import workbench.interfaces.ValidatingComponent;
import workbench.resource.ResourceMgr;

import workbench.gui.WbSwingUtilities;

import workbench.util.GlobalPasswordManager;

/**
 *
 * @author Thomas Kellerer
 */
public class MasterPwdInputForm
  extends JPanel
  implements ValidatingComponent
{
  private final GlobalPasswordManager pwdManager;

  public MasterPwdInputForm(GlobalPasswordManager validator)
  {
    this.pwdManager = validator;
    initComponents();
  }

  @Override
  public boolean validateInput()
  {
    boolean valid = pwdManager.validateMasterPassword(getText());
    if (!valid)
    {
      WbSwingUtilities.showErrorMessageKey(this, "MsgWrongPassword");
    }
    return valid;
  }

  public String getText()
  {
    return pwdInput.getText();
  }

  @Override
  public void componentDisplayed()
  {
  }

  @Override
  public void componentWillBeClosed()
  {
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    pwdInput = new javax.swing.JPasswordField();
    titleLabel = new javax.swing.JLabel();

    setLayout(new java.awt.GridBagLayout());

    pwdInput.setColumns(40);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
    add(pwdInput, gridBagConstraints);

    titleLabel.setText(ResourceMgr.getString("MsgEnterMasterPwd")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    add(titleLabel, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPasswordField pwdInput;
  private javax.swing.JLabel titleLabel;
  // End of variables declaration//GEN-END:variables
}
